fix: Also set crypto provider in `configure_client_insecure` (#57)
This fixes a panic for me, when code is using
`irpc::util::quinn_setup_util::make_insecure_client_endpoint`, where
`configure_client_insecure` wouldn't tell rustls which crypto provider
to use.

<details>
<summary>The panic in question</summary>

```
thread 'tokio-runtime-worker' panicked at /home/philipp/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.31/src/crypto/mod.rs:249:14:

Could not automatically determine the process-level CryptoProvider from Rustls crate features.
Call CryptoProvider::install_default() before this point to select a provider manually, or make sure exactly one of the 'aws-lc-rs' and 'ring' features is enabled.
See the documentation of the CryptoProvider type for more information.
            
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_display
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:269:5
   3: core::option::expect_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/option.rs:2049:5
   4: core::option::Option<T>::expect
             at /home/philipp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:958:21
   5: rustls::crypto::CryptoProvider::get_default_or_install_from_crate_features
             at /home/philipp/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.31/src/crypto/mod.rs:248:24
   6: rustls::client::client_conn::ClientConfig::builder_with_protocol_versions
             at /home/philipp/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.31/src/client/client_conn.rs:317:13
   7: rustls::client::client_conn::ClientConfig::builder
             at /home/philipp/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.31/src/client/client_conn.rs:294:9
   8: irpc::util::quinn_setup_utils::configure_client_insecure
             at /home/philipp/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/irpc-0.7.0/src/util.rs:57:22
   9: irpc::util::quinn_setup_utils::non_wasm::make_insecure_client_endpoint
             at /home/philipp/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/irpc-0.7.0/src/util.rs:93:30
```

</details>